### ISSUE TITLE
composable-glsl-transforms.js server version not updated when running locally

### ISSUE THREAD

**Issue by TheWispy** [ojack/hydra-synth#1]
` osc(...).color(...).sub is not a function`
### glsl-transforms.js
```
  sub: {
    transformType: 'color',
    inputs: [
      {
        name: 'src',
        type: 'image'
      }
    ],
    fragBody: `
      c -= texture2D(<0>, uv);
    `
  }
```
### composable-glsl-functions.js
```
sub: {
    type: 'combine',
    inputs: [
      {
        name: 'color',
        type: 'vec4'
      },
      {
        name: 'amount',
        type: 'float',
        default: 0.5
      }
    ],
    glsl: `vec4 sub(vec4 c0, vec4 c1, float amount){
            return (c0-c1)*amount + c0*(1.0-amount);
          }`
  }
```
### Issue
Running a local version of hydra referring to the current version of hydra-synth rather than the package. I've bee trying to add a subtract function, but despite me editing the glsltransforms section the editor doesn't recognise it as a function. On inspection the server version of composable-glsl-transforms isn't updated with my changes. Do I need to run anything else, or am I missing something?

Cheers 👍

**Comment by ojack** [comment]
Hi ! The documentation is a little left over from when everything was in one repo. So the editor (in github repo hydra) is referencing the version that is uploaded to npm.... if you reference a local copy of hydra-synth, you should be able to edit and update.

This isn't ideal for developing ! In the future I would like to define a way to add functions either before initializing or while running.

**Comment by ojack** [comment]
Dynamically adding functions is now possible, working on documentation.
