### ISSUE TITLE
GeneratorFactory assumes global mode

### ISSUE THREAD

**Issue by micuat** [ojack/hydra-synth#10]
https://github.com/ojack/hydra-synth/blob/master/src/GeneratorFactory.js#L81

doesn't work in `makeGlobal: false` as `src` is assuming global. Quick&dirty fix is to pass hydra instance to GeneratorFactory to formatArguments but maybe there's a better way by unpacking `typedArg` later?

**Comment by ojack** [comment]
This is fixed in recent updates
