### ISSUE TITLE
resolution.xy

### ISSUE THREAD

**Issue by brucelane** [ojack/hydra-synth#11]
put resolution.xy where necessary instead of resolution because sharing the shader to some apps resolution is a vec3:
- in GeneratorFactory.js line 227 vec2 st = gl_FragCoord.xy/resolution; modify to resolution.xy
- same in ShaderManager.js line 11
- in composable-glsl-functions.js line 865

**Comment by sgobotta** [comment]
This should be closed, right?

**Comment by ojack** [comment]
Yes!
