### ISSUE TITLE
Dynamically setting canvas width & height

### ISSUE THREAD

**Issue by jhwoodward** [ojack/hydra-synth#14]
Hi ! I'm really enjoying this fantastic piece of work !  

Any progress on dynamically setting the canvas width / height, or exposing these as options on the api ?

Thanks !

**Comment by misterinterrupt** [comment]
@jhwoodward you can change these via css, is that not going to work for something you are doing?

**Comment by ojack** [comment]
Just added this: https://github.com/ojack/hydra-synth/commit/4c71ad0484d56daf0f83e4268a92cc46872dfe68

You can change it via hydra.resize(width, height)

this changes the resolution of the underlying canvas. To change how it appears on the screen, use CSS.

**Comment by jhwoodward** [comment]
Brilliant ! thanks !
