### ISSUE TITLE
Slow down (or speed up) time

### ISSUE THREAD

**Issue by rseymour** [ojack/hydra-synth#31]
It would be neat to be able to slow-down some of the faster moving animations, but keep them smooth.  Ideally by a sort of slow down / speed up factor, ie 10x, 0.25x, etc.  If it could be applied to everything running it could lead to cool effects if it were parameterized as well.  I mainly want it to make flashier stuff into more atmospheric smooth stuff.

**Comment by ojack** [comment]
Oh I really like this idea. It would be relatively easy to implement, just involve exposing the 'time' variable and allowing users to manage it if desired.

**Comment by brucelane** [comment]
yes, would be useful to use a tempo variable or function so 'time' could be used according to the tempo. sin(time) would be at 0 at each measure for example.

**Comment by ojack** [comment]
There is now a speed variable that controls the rate that time is changing. It is 1 by default, -1 makes everything go in reverse.

(You can still do this manually, as before,  by setting autoLoop to false and passing in your own values of dt :) )
