### ISSUE TITLE
Hydra code as HTML backgroud - without Node?

### ISSUE THREAD

**Issue by AlexandreRangel** [ojack/hydra-synth#36]
Hello! Is is possible to have an Hydra scene running as a HTML background?
Is it possible to run an Hydra-Synth without Node.js on the server?
My hosting server does not support Node...
It does runs the Hydra-Editor alright. Maybe a way stripping down the editor to run just a specific Hydra code, without the Editor UI?

Thank you!

**Comment by AlexandreRangel** [comment]
I got this working like this... The code for Hydra-Editor, opening my code as default in bundle.js and hiding the Editor interface.

**Comment by zachkrall** [comment]
@AlexandreRangel 

I made an example for this recently if it helps:
https://github.com/zachkrall/hydra-workshop/tree/master/standalone

**Comment by AlexandreRangel** [comment]
Hi @zachkrall !
Much cleaner than my solution. Thank you very much, it sure helps!

**Comment by AlexandreRangel** [comment]
Hi @zachkrall 

Why do I get apparent different canvas resolutions with these methods:

1) my modified editor for presentation:
[](https://www.alexandrerangel.art.br/hydra/hydra-present/public/)

2) your presentation code:
[](http://www.alexandrerangel.art.br/hydra/sketch001/)

I tried changing the canvas resolution to the window.innerWidth or to 1920, but could not increase the resolution...

**Comment by zachkrall** [comment]
@AlexandreRangel ah, yeah it looks like adding default height and width values to the html fixes that 
```
<canvas id="hydra-canvas" width="1920" height="1080"></canvas>
```
but in js you could do
```
const hydra_canvas = document.getElementById("hydra-canvas");
hydra_canvas.width = 1920;
hydra_canvas.height = 1080;
```
and then pass `hydra_canvas` for the canvas option in the Hydra constructor

**Comment by AlexandreRangel** [comment]
Thanks a lot, @zachkrall ! The HTML coded fixes it.
Any way to start the canvas with the window.innerWidth, like the Hydra Editor does?

**Comment by AlexandreRangel** [comment]
One interesting thing to study further... both editor and standalone version run on the iPad Pro 2017 (not on my iPhone 7, thou, as expected).

**Comment by zachkrall** [comment]
@AlexandreRangel just made a pull request that maybe addresses cross device compatibility
#37

**Comment by AlexandreRangel** [comment]
@zachkrall that's a huge step towards making Hydra sketches universal!

**Comment by AlexandreRangel** [comment]
Hi @zachkrall ! How can we add this patch to your Hydra standalone player code?
This will eventually be merged on the main editor too, right?
Thank you!
