### ISSUE TITLE
Clear all buffers?

### ISSUE THREAD

**Issue by amounym** [ojack/hydra-synth#53]
Hi there,

I've looked at all the documentation with no success so I am posting here for some help.
I was wondering if there is a command or a workaround to clear the defaults buffers o0, o1, o2, o3? I've seen that you can clear the source buffers like `s0.clear();` but it doesn't seem to work for the output buffers.

Thank you for your help :)

**Comment by ojack** [comment]
hush() should clear all :)

**Comment by ojack** [comment]
For clearing just one buffer, you can us: solid().out()

**Comment by amounym** [comment]
Thank you very much! :)
