### ISSUE TITLE
a.fft not working on macOs Catalina in atom Hydra

### ISSUE THREAD

**Issue by fracnesco** [ojack/hydra-synth#55]
a.fft doesn't seems to work on macOs Catalina in atom hydra neither using the default mic nor using virtual audio busses such soundflower or blackHole

**Comment by fracnesco** [comment]
Apparently the problem is that macOS Catalina doesn't allow Atom to access to the default audio input device. I couldn't find a way to fix this in the system preferences.

**Comment by ojack** [comment]
Hmm this is not an issue within hydra-synth, but seems to be audio routing on your computer. I am closing for now!

**Comment by zachkrall** [comment]
@fracnesco in system preferences > security & privacy, you can give atom permission to access the microphone

<img width="780" alt="Screen Shot 2020-07-23 at 11 54 50 AM" src="https://user-images.githubusercontent.com/2532937/88308819-8507b380-ccdb-11ea-8a13-edf505aba2a1.png">

**Comment by fracnesco** [comment]
That was what I was trying to do but I am not able to add the atom application to the Allowed devices list on the new version of MacOS

**Comment by zachkrall** [comment]
@fracnesco I'm using macOS 10.15.6 and I'm not experiencing the same issue. Are there errors in the developer console? 

<img width="683" alt="Screen Shot 2020-07-29 at 12 37 41 PM" src="https://user-images.githubusercontent.com/2532937/88827744-59cc0b00-d198-11ea-9954-45f914dd1459.png">

Can you try pasting this code into the console to see if you can get the microphone access prompt to appear?
```
navigator
.getUserMedia({audio:true}, 
(stream) => {
	console.log(stream)
},
(e) => {
	alert('Error capturing audio.');
}
);
```
<img width="983" alt="Screen Shot 2020-07-29 at 12 40 19 PM" src="https://user-images.githubusercontent.com/2532937/88828101-b92a1b00-d198-11ea-8c5c-6965d15a5d82.png">
