### ISSUE TITLE
modulateHue doesn't seem to alter anything

### ISSUE THREAD

**Issue by TheWispy** [ojack/hydra-synth#57]
This has been a bit of a mystery to me for a while now, so I'm not sure if I've just been using it wrong, but here goes.

I don't think I've ever gotten modulateHue to work to modulate one signal by another. I've been using it like this:
`noise(3,1).color(1,0.5,0.5).modulateHue(osc(20),0.3).out()`
and the `modulateHue` component isn't altering the visuals, despite not throwing any errors directly to the console. I've potentially been using this wrong, but I've never really seen this function being used at all, so I can't be certain.

This issue was present on hydra.ojack.xyz as of 09/07/2020 in Firefox 78.0.1 (Windows). I'm yet to try it with a local build.

**Comment by ojack** [comment]
modulateHue() is sort of an anomaly / outlier, but you have to use really large values for the second parameter:

https://hydra.ojack.xyz/?code=JTJGJTJGJTIwbW9kdWxhdGVIdWUoKSUyMGV4YW1wbGUlMEElMkYlMkYlMjBvX2phY2slMEElMjAlMEFvc2MoMjAlMkMlMjAwLjElMkMwLjkpJTBBJTA5LmJsZW5kKG8wJTJDJTIwMC45NCklMEElMjAlMjAlMjAlMjAubW9kdWxhdGVIdWUobzAlMkMlMjA0KSUwQSUyMCUyMCUyMCUyMC5zYXR1cmF0ZSgxLjEpJTBBJTIwJTIwJTIwJTIwLm91dCgp

**Comment by TheWispy** [comment]
Yeah I definitely misunderstood what modulateHue does, as I thought it would rotate the hue based on the input. Cheers for clarifying!
