### ISSUE TITLE
don't automatically connect microphone

### ISSUE THREAD

**Issue by charlieroberts** [ojack/hydra-synth#60]
It'd be great to not ask users for mic permissions when a sketch doesn't require it (similar to how the camera currently works). I'm not sure exactly what the best way to do this would be without changing the API... perhaps add a getter method for `a` or `a.fft` with an if statement to check and see if the mic has been initialized... if it hasn't go ahead and ask for permission and initialize it, if it has just return the requested member variable.

**Comment by ojack** [comment]
This should work with detectAudio = false in the init options? Let me know if not!

**Comment by ojack** [comment]
Oh wait, I just realized you are asking something different :)

**Comment by charlieroberts** [comment]
Actually, I think that's exactly what I needed, as I just wanted to turn the FFT / mic input off, so thanks! But I could imagine other use cases where conditionally asking for mic permissions if `a.fft` was used in a script would be nice... anyways, that option works for me so I'll close this.
