### ISSUE TITLE
readme for dev needs update

### ISSUE THREAD

**Issue by micuat** [ojack/hydra-synth#80]
https://github.com/ojack/hydra-synth/blame/master/README.md#L16

the command no longer exists. The proper sequence should be 

    npm install
    npm run build

and I don't know why but in my environment, build fails with EACCES when outputting to a bundle with `>`. I had to change it to

```
    "build-hydra": "browserify hydra-synth.js --standalone Hydra | tee dist/hydra-synth.js",
    "build-shader-generator": "browserify shader-generator.js --standalone HydraShaders | tee dist/hydra-shaders.js",
```

not sure if this is related to the installation of browserify

**Comment by micuat** [comment]
is actually `build-shader-generator` a thing? i think normally `npm run build-hydra` is enough

**Comment by ojack** [comment]
The shader generator is a work in progress separated module, that can do the shader generation / parsing capabilities of hydra without needing webgl. So you could run server-side or in a lot of other contexts.

**Comment by micuat** [comment]
This EACCES error may be caused because of `live-server` running in the background at the root (I could reproduce the issue and closing the server seemed to solve the problem). If anyone encountered the same issue, try `live-server` inside dist directory.
