### ISSUE TITLE
iOS initCam fix

### ISSUE THREAD

**Issue by micuat** [ojack/hydra-synth#99]
currently initCam on iOS fails because of this 

https://stackoverflow.com/questions/53483975/navigator-mediadevices-getusermedia-not-working-on-ios-12-safari

which means

```javascript
    video.setAttribute('autoplay', '');
    video.setAttribute('muted', '');
    video.setAttribute('playsinline', '');
```

has to be added here

https://github.com/ojack/hydra-synth/blob/main/src/lib/webcam.js#L19

I can't make PR right now but quickly test that it works by editing the bundled hydra-synth

https://midnight-substantial-oxygen.glitch.me/

**Comment by ojack** [comment]
Oh wow, this is amazing! Trying it out now.

**Comment by ojack** [comment]
Updated here!: [3dda97503fbd2167633405de811b18e0440875be](https://github.com/ojack/hydra-synth/commit/3dda97503fbd2167633405de811b18e0440875be)
